@url_dev = http://localhost:3055/v1/api

### Create New Product
POST {{url_dev}}/shop/product
Content-Type: application/json
x-api-key: df0fa8e478e8149581b2994fd3f717422dbb7a8f1d578afd233a506f8fd02f90306a7946f3c4abb2089889c081326d05a848caf9f495286aca11ff4aea2479fa
x-client-id: 683d778c7c437e68030d237e
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODNkNzc4YzdjNDM3ZTY4MDMwZDIzN2UiLCJlbWFpbCI6ImFiY0oxQGdtYWlsLmNvbSIsImlhdCI6MTc0OTI4NTAyMCwiZXhwIjoxNzQ5NDU3ODIwfQ.hNsN1TheShSpqbXwTs6sHctfJTA-25VN1LGAjvwxY2c

{
  "product_name": "Wireless Mouse",
  "product_thumb": "https://example.com/images/wireless-mouse.jpg",
  "product_description": "A sleek wireless mouse with ergonomic design and long battery life.",
  "product_price": 25.99,
  "product_quantity": 100,
  "product_type": "Electronics",
  "product_attributes": {
    "color": "black",
    "manufacturer": "Logitech",
    "model": "M185"
  }
}


### Get List Product Draft
GET {{url_dev}}/shop/product-draft
Content-Type: application/json
x-api-key: df0fa8e478e8149581b2994fd3f717422dbb7a8f1d578afd233a506f8fd02f90306a7946f3c4abb2089889c081326d05a848caf9f495286aca11ff4aea2479fa
x-client-id: 683d778c7c437e68030d237e
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODNkNzc4YzdjNDM3ZTY4MDMwZDIzN2UiLCJlbWFpbCI6ImFiY0oxQGdtYWlsLmNvbSIsImlhdCI6MTc0OTI4NTAyMCwiZXhwIjoxNzQ5NDU3ODIwfQ.hNsN1TheShSpqbXwTs6sHctfJTA-25VN1LGAjvwxY2c

{
  "skip": 0,
  "limit": 0
}

### Get List Product Publish
GET {{url_dev}}/shop/product-publish
Content-Type: application/json
x-api-key: df0fa8e478e8149581b2994fd3f717422dbb7a8f1d578afd233a506f8fd02f90306a7946f3c4abb2089889c081326d05a848caf9f495286aca11ff4aea2479fa
x-client-id: 683d778c7c437e68030d237e
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODNkNzc4YzdjNDM3ZTY4MDMwZDIzN2UiLCJlbWFpbCI6ImFiY0oxQGdtYWlsLmNvbSIsImlhdCI6MTc0OTI4NTAyMCwiZXhwIjoxNzQ5NDU3ODIwfQ.hNsN1TheShSpqbXwTs6sHctfJTA-25VN1LGAjvwxY2c

{
  "skip": 0,
  "limit": 0
}

### Publish Product
PATCH  {{url_dev}}/shop/product-publish?productId=6845aa290c314d44c54342f6 
Content-Type: application/json
x-api-key: df0fa8e478e8149581b2994fd3f717422dbb7a8f1d578afd233a506f8fd02f90306a7946f3c4abb2089889c081326d05a848caf9f495286aca11ff4aea2479fa
x-client-id: 683d778c7c437e68030d237e
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODNkNzc4YzdjNDM3ZTY4MDMwZDIzN2UiLCJlbWFpbCI6ImFiY0oxQGdtYWlsLmNvbSIsImlhdCI6MTc0OTI4NTAyMCwiZXhwIjoxNzQ5NDU3ODIwfQ.hNsN1TheShSpqbXwTs6sHctfJTA-25VN1LGAjvwxY2c
